server:
  port: 8081

spring:
  application: 
    name: payment-service # 命名在註冊 Eureka 時會對應其 Application
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none #避免spring-data-jpa啟動時重建database
  h2:
    console:
      enabled: true
      path: /h2-console
      
# 搭配 Eureka 註冊服務 定時向 server 發送存活的請求      
eureka:
  client:
    register-with-eureka: true # 將client註冊進 eureka
    fetch-registry: true # 從eureka抓取 註冊消息, 如果為eureka集群, 要true 才能達到 load balance
    service-url:
      defaultZone: http://localhost:7001/eureka