server:
  port: 6001
  
# 搭配 Eureka 註冊服務 定時向 server 發送存活的請求      
eureka:
  instance:
    hostname: cloud-config
    instance-id: cloud-config # eureka 顯示服務別名
    prefer-ip-address: true # 顯示服務IP address
  client:
    register-with-eureka: true # 將client註冊進 eureka
    fetch-registry: true # 從eureka抓取 註冊消息, 如果為eureka集群, 要true 才能達到 load balance
    service-url:
      defaultZone: http://eureka-server.com:7001/eureka

spring:
  application: 
    name: cloud-config # 命名在註冊 Eureka 時會對應其 Application
  cloud:
    config:
      server:
        git:
          # repository 
          uri: # 請填入自己建立的 configuration repository
          # directory (路徑放在根目錄底下, 因此 search-paths 填空)
          search-paths:
            - 
          username: # 請填入 git username
          password: # 請填入 git password
      # target branch
      label: master