server:
  port: 8083
  
spring:
  application: 
    name: payment-hystrix-service # 命名在註冊 Eureka 時會對應其 Application  

# 搭配 Eureka 註冊服務 定時向 server 發送存活的請求      
eureka:
  client:
    register-with-eureka: true # 將client註冊進 eureka
    fetch-registry: true # 從eureka抓取 註冊消息, 如果為eureka集群, 要true 才能達到 load balance
    service-url:
      defaultZone: http://eureka-server.com:7001/eureka # 註冊eureka 群集
  instance:
    instance-id: payment-hystrix-service # eureka 顯示服務別名
    prefer-ip-address: true # 顯示服務IP address